### ISSUE TITLE
Not propagating variables correctly

### ISSUE THREAD

**Issue by kress95** [codemix/babel-plugin-closure-elimination#16]
This code:
https://gist.github.com/kress95/cb512facbb1f3077a74daf4e9e15c2ab/66fcb53504ce5904794f728be5d544300a3e5c9a

is yielding this code:
https://gist.github.com/kress95/cb512facbb1f3077a74daf4e9e15c2ab/58d552ccae1fb762ab81293e0bcd541a6be99ff3

that is throwing this error:
https://gist.github.com/kress95/cb512facbb1f3077a74daf4e9e15c2ab/a1afb972713635a9eb1fe5318bb0a1f6af92f6d6

(using latest version on NPM)

**Comment by Ceane** [comment]
I'm having the same issue with variables locally defined

**Comment by Gvozd** [comment]
@kress95 , please try version 1.1.0
Your case can fixed
